# file: switch_vlan_create_modify.yml
- hosts: switch1
  tasks:
  - name: gather facts from switch
    comware_5_2:
      host={{ switch_host }}
      username={{ switch_user }}
      password={{ switch_password }}

  - name: create VLAN_44
    comware_5_2_vlan:
      host={{ switch_host }}
      username={{ switch_user }}
      password={{ switch_password }}
      state=present
      vlan_id=44
      vlan_name=VLAN_44
      untagged_port_type=access
      untagged_ports=GigabitEthernet1/0/9,GigabitEthernet1/0/10

  - name: modify VLAN_44
    comware_5_2_vlan:
      host={{ switch_host }}
      username={{ switch_user }}
      password={{ switch_password }}
      state=present
      vlan_id=44
      vlan_name=VLAN_44
      untagged_port_type=access
      untagged_ports=GigabitEthernet1/0/9,GigabitEthernet1/0/10,GigabitEthernet1/0/28
      tagged_port_type=hybrid
      tagged_ports=GigabitEthernet1/0/27

  - name: delete VLAN_44
    comware_5_2_vlan:
      host={{ switch_host }}
      username={{ switch_user }}
      password={{ switch_password }}
      state=absent
      vlan_id=44
      vlan_name=VLAN_44
